security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Users:
            algorithm: auto
    providers:
        api_user_provider:
            entity:
                class: App\Entity\Users
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern: ^/api/login
            provider: api_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\LoginAuthenticator
        api_registration:
            pattern: ^/api/register
            security: false
        main:
            pattern: /api
            provider: api_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\APIAuthenticator
    access_control:
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        logout:
#        path: app_logout
#        clear_site_data:
#             - cookies
#             - storage
#        target: /
#    required_badges: ['CsrfTokenBadge', 'My\Badge']